name: api-deploy-dev

on:
  workflow_call:
    secrets:
      ARTIFACTORY_NPM_REGISTRY:
        required: true
      ARTIFACTORY_AUTH:
        required: true
      ARTIFACTORY_EMAIL:
        required: true
      AZURE_SUBSCRIPTION_ID: 
        required: true
      AZURE_TENANT_ID:
        required: true
      AZURE_CLIENT_ID:
        required: true
      AZURE_CLIENT_SECRET:
        required: true
      AZURE_FUNCTIONS_APP_ID:
        required: true
      AZURE_FUNCTIONS_SECRET:
        required: true
      AZURE_REGION_DEV:
        required: true
      AZURE_RESOURCE_GROUP_DEV:
        required: true
        
      AWS_ACCESS_KEY_ID_DEV:
        required: false
      AWS_SECRET_ACCESS_KEY_DEV:
        required: false
      AWS_REGION_DEV:
        required: false

      ENV_DEV:
        required: true
      
      LOG_LEVEL_DEV:
        required: false
            
      DD_API_KEY:
        required: false

      DATABASE_HOST_DEV:
        required: true
      DATABASE_USERNAME_DEV:
        required: true
      DATABASE_PASSWORD_DEV:
        required: true
      DATABASE_NAME_DEV:
        required: true

      EMAIL_PROVIDER_DEV:
        required: false
      EMAIL_USERNAME_DEV:
        required: false
      EMAIL_PASSWORD_DEV:
        required: false

      KEYCLOAK_URL_DEV:
        required: false
      KEYCLOAK_USERNAME_ADMIN_DEV:
        required: false
      KEYCLOAK_PASSWORD_ADMIN_DEV:
        required: false
      
      EVENTBUS_NAME:
        required: false
      EVENTBUS_SOURCE:
        required: false
      EVENTBUS_DETAIL_TYPE:
        required: false
      
      NAVEGA_API_URL_DEV:
        required: false

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    container: f3capital/aquario:latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    env:
      AZURE_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
      AZURE_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
      AZURE_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
      AZURE_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
      AZURE_REGION: ${{secrets.AZURE_REGION_DEV}}
      AZURE_STAGE: ${{secrets.ENV_DEV}}
      AZURE_RESOURCE_GROUP: ${{secrets.AZURE_RESOURCE_GROUP_DEV}}

      DATABASE_HOST: ${{secrets.DATABASE_HOST_DEV}}
      DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME_DEV}}
      DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD_DEV}}
      DATABASE_NAME: ${{secrets.DATABASE_NAME_DEV}}
      
      EMAIL_PROVIDER: ${{ secrets.EMAIL_PROVIDER_DEV }}
      EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME_DEV }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD_DEV }}
      
      KEYCLOAK_URL: ${{secrets.KEYCLOAK_URL_DEV}}
      KEYCLOAK_USERNAME_ADMIN: ${{secrets.KEYCLOAK_USERNAME_ADMIN_DEV}}
      KEYCLOAK_PASSWORD_ADMIN: ${{secrets.KEYCLOAK_PASSWORD_ADMIN_DEV}}
      
      EVENTBUS_NAME: ${{ secrets.EVENTBUS_NAME }}
      EVENTBUS_REGION: ${{ secrets.AWS_REGION_DEV }}
      EVENTBUS_SOURCE: ${{ secrets.EVENTBUS_SOURCE }}
      EVENTBUS_DETAIL_TYPE: ${{ secrets.EVENTBUS_DETAIL_TYPE }}
      EVENTBUS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
      EVENTBUS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
    
      NAVEGA_API_URL: ${{ secrets.NAVEGA_API_URL_DEV }}
      
      ENV: ${{ secrets.ENV_DEV }}
      DD_API_KEY: ${{ secrets.DD_API_KEY }}
      LOG_LEVEL: ${{ secrets.LOG_LEVEL_DEV }}
      
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          
      - name: Install
        run: |
          npm config set registry ${{secrets.ARTIFACTORY_NPM_REGISTRY}}
          npm config set -- '_auth' "${{secrets.ARTIFACTORY_AUTH}}"
          npm config set -- 'email' "${{secrets.ARTIFACTORY_EMAIL}}"
          npm config set -- 'always-auth' "true"
          yarn install
      
      - name: Development Deploy 
        run: |
          export APP_NAME=$(node -p "require('./package.json').name")
          sls package
          az login --service-principal --username ${{secrets.AZURE_FUNCTIONS_APP_ID}} --password ${{secrets.AZURE_FUNCTIONS_SECRET}} --tenant ${{secrets.AZURE_TENANT_ID}}
          az functionapp deployment source config-zip -g ${{secrets.AZURE_RESOURCE_GROUP_DEV}} -n aquario-eus2-dev-$APP_NAME --src .serverless/$APP_NAME.zip
          sls deploy
          az functionapp deployment source config-zip -g ${{secrets.AZURE_RESOURCE_GROUP_DEV}} -n aquario-eus2-dev-$APP_NAME --src .serverless/$APP_NAME.zip

